### PR TITLE
Dj add recommendation placeholder

### LINKED ISSUE #11: Add Recommendation menu to nav bar
- [x] There is a pull down menu on the Nav bar with the label `Recommendations`
- [x] When that label is clicked, we see a menu with a single open: `List Recommendations`.
- [x] When the `List Recommendations` option is selected, the browser window goes to the route `/recommmendations/list`
- [x] There is full test code coverage on Codecov for new code
- [x] There is full mutation test coverage on Pitest for new code

### LINKED ISSUE #12: Add Placeholder for Recommendation Index Page
- [x] There is a web page at the path ```recommendations/list```. 
- [x] That web page says "This is where the index page will go".
- [x] That web page can be accessed from the nav bar recommendation menu.
- [x] There is full test code coverage on Codecov for new code
- [x] There is full mutation test coverage on Stryker for new code

### PR DESCRIPTION
**Pull request by D-Jerez**
# Overview

I've added the Recommendation menu to the Nav bar, and added a placeholder page for Recommendation's index page.

I'm also adding my team02 stuff (backend CRUD operations) in this PR so that I can get started on the table.

# Issues Addressed

This resolves issues #11 (Add Recommendation Menu to Nav Bar) and #12 (Add Placeholder for Recommendation Index Page). 

# Details

Here's the placeholder page, and the Nav bar with the Recommendation drop down menu.
image:
image
image

# Test Plan (for interactive testing)

Run the frontend and backend locally (on localhost 8080), and log in with a gmail account (this is a user feature, so which account you use doesn't matter). Click on "Recommendations", and click "List Recommendations". This should lead to the page in the screenshot.

You can also run ```npm run coverage``` to view code coverage of tests, and ```npx stryker run``` to run mutation testing.

### CODE REVIEW

**Review by zackmarks — APPROVED** [review]
LGTM

**Review by Yvonneliu0201 — APPROVED** [review]
lgtm

**Review by Yvonneliu0201 — CHANGES_REQUESTED** [review]
add the tests for the backend controller for recommendation in order to have full code coverage

**Review by Yvonneliu0201 — APPROVED** [review]
lgtm

**Pull request merged**
